version: '3.8'

services:
  yield-claimer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yield-claimer-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NETWORK=${NETWORK:-TESTNET}
      - WALLET_SECRET_KEY=${WALLET_SECRET_KEY}
      - WALLET_PUBLIC_KEY=${WALLET_PUBLIC_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - yield-claimer-network

networks:
  yield-claimer-network:
    driver: bridge